/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TechBadgeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "techBadge";
};

export type StackCategory = {
  _id: string;
  _type: "stackCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  technologies?: Array<{
    _key: string;
  } & TechBadgeReference>;
  order?: number;
};

export type TechBadge = {
  _id: string;
  _type: "techBadge";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key?: string;
  name?: string;
  icon?: string;
  color?: string;
};

export type Certification = {
  _id: string;
  _type: "certification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  title?: string;
  subtitle?: string;
  link?: string;
  tag?: string;
  isCourse?: boolean;
  order?: number;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  title?: string;
  subtitle?: string;
  link?: string;
  tag?: string;
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  title?: string;
  subtitle?: string;
  link?: string;
  tag?: string;
  order?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tag?: string;
  description?: string;
  video?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  credits?: string;
  link?: string;
  googlePlay?: string;
  appStore?: string;
  technologies?: Array<{
    _key: string;
  } & TechBadgeReference>;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pills?: Array<string>;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  background?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "closing";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  resumeIntro?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLines?: Array<string>;
  taglineLines?: Array<string>;
  featuredHeading?: {
    number?: string;
    titleLine1?: string;
    titleLine2?: string;
  };
  aboutHeading?: {
    number?: string;
    titleLine1?: string;
    titleLine2?: string;
  };
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  timezone?: string;
  resumeFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  signature?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: {
    title?: string;
    description?: string;
    ogDescription?: string;
    shortDescription?: string;
    keywords?: Array<string>;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  socials?: Array<{
    label?: string;
    url?: string;
    _type: "social";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes = TechBadgeReference | StackCategory | TechBadge | Certification | Education | Experience | SanityImageAssetReference | Project | SanityImageCrop | SanityImageHotspot | AboutPage | HomePage | SanityFileAssetReference | SiteSettings | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;

// Source: ../src/sanity/queries.ts
// Variable: HOME_QUERY
// Query: {  "siteSettings": *[_type == "siteSettings"][0]{    name,    role,    timezone,    avatar {  alt,  asset->{    url,    metadata { lqip, dimensions { width, height } }  }},    signature {  alt,  asset->{    url,    metadata { lqip, dimensions { width, height } }  }},    "resumeUrl": resumeFile.asset->url  },  "homePage": *[_type == "homePage"][0]{    heroLines,    taglineLines,    featuredHeading { number, titleLine1, titleLine2 },    aboutHeading { number, titleLine1, titleLine2 }  },  "aboutPage": *[_type == "aboutPage"][0]{    pills,    portrait {  alt,  asset->{    url,    metadata { lqip, dimensions { width, height } }  }},    background,    resumeIntro  },  "projects": *[_type == "project"] | order(order asc){    _id,    title,    tag,    description,    video,    credits,    link,    googlePlay,    appStore,    image {  alt,  asset->{    url,    metadata { lqip, dimensions { width, height } }  }},    technologies[]->{ _id, name, icon, color }  },  "experience": *[_type == "experience"] | order(order asc){    _id, date, title, subtitle, link, tag  },  "education": *[_type == "education"] | order(order asc){    _id, date, title, subtitle, link, tag  },  "certifications": *[_type == "certification"] | order(order asc){    _id, date, title, subtitle, link, tag, isCourse  },  "stackCategories": *[_type == "stackCategory"] | order(order asc){    _id,    title,    technologies[]->{ _id, name, icon, color }  }}
export type HOME_QUERY_RESULT = {
  siteSettings: {
    name: string | null;
    role: string | null;
    timezone: string | null;
    avatar: {
      alt: null;
      asset: {
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
    signature: {
      alt: null;
      asset: {
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
    resumeUrl: string | null;
  } | null;
  homePage: {
    heroLines: Array<string> | null;
    taglineLines: Array<string> | null;
    featuredHeading: {
      number: string | null;
      titleLine1: string | null;
      titleLine2: string | null;
    } | null;
    aboutHeading: {
      number: string | null;
      titleLine1: string | null;
      titleLine2: string | null;
    } | null;
  } | null;
  aboutPage: {
    pills: Array<string> | null;
    portrait: {
      alt: null;
      asset: {
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
    background: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "closing" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    resumeIntro: string | null;
  } | null;
  projects: Array<{
    _id: string;
    title: string | null;
    tag: string | null;
    description: string | null;
    video: string | null;
    credits: string | null;
    link: string | null;
    googlePlay: string | null;
    appStore: string | null;
    image: {
      alt: null;
      asset: {
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
    technologies: Array<{
      _id: string;
      name: string | null;
      icon: string | null;
      color: string | null;
    }> | null;
  }>;
  experience: Array<{
    _id: string;
    date: string | null;
    title: string | null;
    subtitle: string | null;
    link: string | null;
    tag: string | null;
  }>;
  education: Array<{
    _id: string;
    date: string | null;
    title: string | null;
    subtitle: string | null;
    link: string | null;
    tag: string | null;
  }>;
  certifications: Array<{
    _id: string;
    date: string | null;
    title: string | null;
    subtitle: string | null;
    link: string | null;
    tag: string | null;
    isCourse: boolean | null;
  }>;
  stackCategories: Array<{
    _id: string;
    title: string | null;
    technologies: Array<{
      _id: string;
      name: string | null;
      icon: string | null;
      color: string | null;
    }> | null;
  }>;
};

// Source: ../src/sanity/queries.ts
// Variable: SITE_METADATA_QUERY
// Query: *[_type == "siteSettings"][0]{  name,  role,  seo {    title,    description,    ogDescription,    shortDescription,    keywords,    ogImage { asset->{ url } }  },  "avatarUrl": avatar.asset->url}
export type SITE_METADATA_QUERY_RESULT = {
  name: string | null;
  role: string | null;
  seo: {
    title: string | null;
    description: string | null;
    ogDescription: string | null;
    shortDescription: string | null;
    keywords: Array<string> | null;
    ogImage: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
  avatarUrl: string | null;
} | null;

